package com.example.tello.contacts;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by tello on 28/09/15.
 */
public class Data {
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField(index = true)
    String nom;
    @DatabaseField
    Integer telephone;
    @DatabaseField
    String Email;
    @DatabaseField
    double latitidue;
    @DatabaseField
    double longitdue;


    Data() {
        // needed by ormlite
    }

    public Data(String nom, Integer telephone, String Email, double latitidue, double longitdue) {
        this.nom = nom;
        this.telephone = telephone;
        this.Email = Email;
        this.latitidue = latitidue;
        this.longitdue = longitdue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Name: ").append(nom);
        sb.append("\n---------------------\n").append("Telephone: ").append(telephone);
        sb.append("\n---------------------\n").append("Email: ").append(Email);
        sb.append("\n---------------------\n").append("Latitude: ").append(latitidue);
        sb.append("\n---------------------\n").append("longitude=").append(longitdue);
        return sb.toString();
    }
}
